server:
  port: 8081
spring:
  application:
    name: registry-server
eureka:
  client:
    #是否将eureka自身作为应用注册到eureka注册中心
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://localhost:8081/eureka/
  instance:

    # 服务刷新时间配置，每隔这个时间会主动心跳一次
    # 默认30s
    lease-renewal-interval-in-seconds: 5
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    # 注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    # 默认90s
    lease-expiration-duration-in-seconds: 15
